services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    command: "deno run -A main.ts"
    stdin_open: true
    tty: true
  ruby:
    build:
      context: ./ruby
    volumes:
      - ./ruby:/app
    ports:
      - 4567:4567
    command: "bundle exec ruby app.rb -o 0.0.0.0"
